apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds/kubeflow_pytorchjobs.yaml
  - 01.cluster-role-binding.yaml
  - 02.role.yaml
  - 03.service-account.yaml
  - ./webhook
  - service.yaml
  - deployment.yaml